### ISSUE TITLE
READMEにアプリケーションの説明や使い方、環境情報を記載しましょう

### ISSUE THREAD

**Issue by norotime** [hideaki216/Bukumake#1]
https://github.com/hideaki216/Bukumake/blob/master/README.rdoc

**Comment by norotime** [comment]
@hideaki216 模範例です！
https://github.com/masarusan24/hanaguri-silver/blob/develop/README.md

**Comment by hideaki216** [comment]
READMEにアプリのURL、説明、環境情報、使い方を記載しました。

**Comment by hideaki216** [comment]
コミットとイシューを紐づけました。
