### ISSUE TITLE
%i記法を使いコード量を削減する

### ISSUE THREAD

**Issue by norotime** [hideaki216/Bukumake#2]
https://github.com/hideaki216/Bukumake/blob/21eeb1973cb7f1e29830a39b4359936895d2e490/app/controllers/books_controller.rb#L2

%i!STRING! : 要素がシンボルの配列(空白区切り)
https://docs.ruby-lang.org/ja/latest/doc/spec=2fliteral.html#percent

**Comment by hideaki216** [comment]
Controllerとroutesの配列の表記を%i記法に変更しました。
