### ISSUE TITLE
定番の書籍はシードデータとして登録できるようにしておきましょう

### ISSUE THREAD

**Issue by norotime** [hideaki216/Bukumake#3]
https://github.com/hideaki216/Bukumake/blob/master/db/seeds.rb

@hideaki216 Ruby系の定番書籍は登録しておきませんか？

**Comment by hideaki216** [comment]
書籍のシードデータを登録しました。
本番環境で投入済みです。

**Comment by norotime** [comment]
@hideaki216 いいですね！
式を大量に記載するのではなく、配列にハッシュとして入れるなどして、制御構造を使って作成しませんか？

例：
```
[
  { title: "hoge1", author: "fuga1", user_id: 1 } , 
  { title: "hoge2", author: "fuga2", user_id: 2 }
]
```

**Comment by norotime** [comment]
ハッシュとは
class Hash
https://docs.ruby-lang.org/ja/latest/class/Hash.html

**Comment by norotime** [comment]
制御構造のeach

instance method Array#each
https://docs.ruby-lang.org/ja/latest/method/Array/i/each.html

**Comment by hideaki216** [comment]
制御構造を使ってシードデータを登録・投入、コミットメッセージでクローズしました。
